/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.HamXuLyChung;
import dao.TaiKhoanDAO;
import java.awt.Dimension;

import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import pojo.TaiKhoan;
import java.awt.Dimension;
import java.awt.Graphics;
import pojo.ImageThongBao;

/**
 *
 * @author ADMIN
 */
public class frm_TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form frm_TrangChu
     */
    TaiKhoanDAO tkDAO = new TaiKhoanDAO();
    boolean ktraLogin = false;

    TaiKhoan taiKhoan = new TaiKhoan();
    HamXuLyChung hxl = new HamXuLyChung();
    ImageThongBao imgTB = new ImageThongBao();

    public frm_TrangChu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Trang Chủ");
        this.setSize(1620, 800);
//        this.setResizable(false);
        txtUsername.requestFocus();
        hideThaoTac();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnDangNhap = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnDangNhapC = new javax.swing.JButton();
        btnsachC = new javax.swing.JButton();
        btnMuonTraC = new javax.swing.JButton();
        btnThongTinNVC = new javax.swing.JButton();
        btnNhanVienC = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnDangXuatC = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");

        desktopPane.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(245, 133, 45));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/leftLogin.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QUẢN LÝ THƯ VIỆN");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconSach.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(75, 75, 75)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        desktopPane.add(jPanel2);
        jPanel2.setBounds(-10, 0, 600, 750);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/login1-icon.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new java.awt.GridLayout(2, 1, 0, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setText("Username:");
        jPanel4.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setText("Password:");
        jPanel4.add(jLabel7);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new java.awt.GridLayout(2, 1, 0, 25));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel5.add(txtUsername);

        txtPass.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jPanel5.add(txtPass);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Sign In");

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new java.awt.GridLayout(1, 2, 50, 0));

        btnDangNhap.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/login-icon.png"))); // NOI18N
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseClicked(evt);
            }
        });
        jPanel6.add(btnDangNhap);

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thoat2.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel6.add(btnThoat);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel8)
                        .addGap(58, 58, 58))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel3);
        jPanel3.setBounds(590, 0, 810, 750);

        jPanel1.setLayout(new java.awt.GridLayout(7, 1));

        btnDangNhapC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnDangNhapC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dangnhap.png"))); // NOI18N
        btnDangNhapC.setText("Đăng nhập");
        btnDangNhapC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDangNhapC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapCActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangNhapC);

        btnsachC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnsachC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageSach/iconsach1.png"))); // NOI18N
        btnsachC.setText("Sách");
        btnsachC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnsachC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsachCActionPerformed(evt);
            }
        });
        jPanel1.add(btnsachC);

        btnMuonTraC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnMuonTraC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/doitac.png"))); // NOI18N
        btnMuonTraC.setText("Mượn trả");
        btnMuonTraC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMuonTraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonTraCActionPerformed(evt);
            }
        });
        jPanel1.add(btnMuonTraC);

        btnThongTinNVC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnThongTinNVC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon-user.png"))); // NOI18N
        btnThongTinNVC.setText("Thông tin");
        btnThongTinNVC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThongTinNVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinNVCActionPerformed(evt);
            }
        });
        jPanel1.add(btnThongTinNVC);

        btnNhanVienC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnNhanVienC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nhanvien.png"))); // NOI18N
        btnNhanVienC.setText("Nhân viên");
        btnNhanVienC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhanVienC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienCActionPerformed(evt);
            }
        });
        jPanel1.add(btnNhanVienC);

        btnThongKe.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconTk.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jPanel1.add(btnThongKe);

        btnDangXuatC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnDangXuatC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thoat.png"))); // NOI18N
        btnDangXuatC.setText("Đăng xuất");
        btnDangXuatC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDangXuatC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatCActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangXuatC);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1349, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanVienCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienCActionPerformed
        // TODO add your handling code here:
        xoaManHinh();
        frm_NhanVien nv = new frm_NhanVien();
        this.desktopPane.add(nv);
        nv.setVisible(true);
        nv.loadAccount(taiKhoan.getUsername());
        
    }//GEN-LAST:event_btnNhanVienCActionPerformed

    private void btnsachCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsachCActionPerformed
        // TODO add your handling code here:
        xoaManHinh();
        frm_Sach sach = new frm_Sach();
        this.desktopPane.add(sach);
        sach.setVisible(true);
    }//GEN-LAST:event_btnsachCActionPerformed

    private void btnMuonTraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonTraCActionPerformed
        xoaManHinh();
        frm_MuonTra muonTra = new frm_MuonTra();//đưa mã nhân viên qua frame mượn trả

        this.desktopPane.add(muonTra);
        muonTra.setVisible(true);
        muonTra.chonMaNVHienHanh(taiKhoan.getMaNV());
//        muonTra.setMaNhanVien(taiKhoan.getMaNV());
    }//GEN-LAST:event_btnMuonTraCActionPerformed

    private void btnDangNhapCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapCActionPerformed
        xoaManHinh();
    }//GEN-LAST:event_btnDangNhapCActionPerformed

    private void btnDangXuatCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatCActionPerformed
        int n = JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,imgTB.getImgQuestion());
        if (n == JOptionPane.YES_OPTION) {
            hideThaoTac();
            btnDangNhapC.setEnabled(true);

            xoaManHinh();
            txtPass.setText("");
            txtUsername.requestFocus();
        }

    }//GEN-LAST:event_btnDangXuatCActionPerformed

    private void btnThongTinNVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinNVCActionPerformed
        xoaManHinh();
        frm_InfoNhanVien ifnv = new frm_InfoNhanVien();
        this.desktopPane.add(ifnv);
        ifnv.setVisible(true);
        ArrayList<TaiKhoan> lstTK = tkDAO.listTaiKhoan();
        for (TaiKhoan tk : lstTK) {
            if (tk.getUsername().equals(taiKhoan.getUsername())) {
                taiKhoan.setPassword(tk.getPassword());
                break;
            }
        }
        ifnv.loadInfoNhanVien(taiKhoan.getUsername(), taiKhoan.getPassword(), taiKhoan.getMaNV(), taiKhoan.getTenNV(), taiKhoan.getSdt(), taiKhoan.getGioiTinh(), taiKhoan.getNgaySinh().toString(), taiKhoan.getHinh(), taiKhoan.getLuong(), taiKhoan.getCmnd(), taiKhoan.getEmail());
        ifnv.reloadInfoNhanVien();
    }//GEN-LAST:event_btnThongTinNVCActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        xoaManHinh();
        frm_ThongKe ifTK = new frm_ThongKe();
        this.desktopPane.add(ifTK);
        ifTK.setVisible(true);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseClicked
        ArrayList<TaiKhoan> lstTK = tkDAO.listTaiKhoan();
        if (txtUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Tài khoản không được trống","Thông báo",1,imgTB.getImgWarning());
            txtUsername.setText("");
            txtUsername.requestFocus();
        } else if (txtPass.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu không được trống","Thông báo",1,imgTB.getImgWarning());
            txtPass.setText("");
            txtPass.requestFocus();
        } else {

            String user = txtUsername.getText().trim();
            String pass = hxl.getHashMD5(txtPass.getText().trim());

            int ktraTKLogin = 0;
            int ktraMKLogin = 0;
            int ktraAdmin = 0;
            int ktraTKLock = 1;
            //kiểm tra tên đăng nhập tồn tại
            for (TaiKhoan tk : lstTK) {
                if (tk.getUsername().trim().equals(user)) {
                    ktraTKLogin = 1;
                    break;
                }
            }
            //kiểm tra Account đã bị khóa
            for (TaiKhoan tk : lstTK) {
                if (tk.getUsername().trim().equals(user) && tk.getLoaiTK().equals("lock")) {
                    ktraTKLock = 0;
                    break;
                }
            }
            if (ktraTKLogin == 0) {
                JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập không chính xác!","Thông báo",1,imgTB.getImgWarning());
                txtUsername.requestFocus();
            } else if (ktraTKLock == 0) {
                JOptionPane.showMessageDialog(rootPane, "Tài khoản này đã bị khóa.\nLiên hệ quản lý để biết thêm thông tin.!", "Thông báo", 0,imgTB.getImgError());
                txtUsername.requestFocus();
            } else {

                //kiểm tra mật khẩu
                for (TaiKhoan tk : lstTK) {
                    if (tk.getUsername().trim().equals(user) && tk.getPassword().trim().equals(pass)) {
                        ktraMKLogin = 1;
                        taiKhoan = tk;
                        break;
                    }
                }
                if (ktraMKLogin == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Mật khẩu không chính xác!","Thông báo",1,imgTB.getImgWarning());
                    txtPass.setText("");
                    txtPass.requestFocus();
                } else {
                    //Kiểm tra Tài khoản của admin hay nhân viên thường
                    for (TaiKhoan tk : lstTK) {
                        if (tk.getUsername().trim().equals(user) && tk.getLoaiTK().trim().equals("ad")) {
                            ktraAdmin = 1;
                            break;
                        }
                    }

                    if (ktraAdmin == 0) {//Mở quyền nhân  viên
                        showThaoTac();
                        btnNhanVienC.setEnabled(false);
                        btnDangNhapC.setEnabled(false);
                        xoaManHinh();
                        frm_InfoNhanVien frNV = new frm_InfoNhanVien();
                        desktopPane.add(frNV);
                        frNV.setVisible(true);
                        frNV.loadInfoNhanVien(taiKhoan.getUsername(), taiKhoan.getPassword(), taiKhoan.getMaNV(), taiKhoan.getTenNV(), taiKhoan.getSdt(), taiKhoan.getGioiTinh(), taiKhoan.getNgaySinh().toString(), taiKhoan.getHinh(), taiKhoan.getLuong(), taiKhoan.getCmnd(), taiKhoan.getEmail());

                    } else {//Mở quyền admin
                        showThaoTac();
                        btnDangNhapC.setEnabled(false);

                        xoaManHinh();
                        frm_InfoNhanVien frNV = new frm_InfoNhanVien();
                        desktopPane.add(frNV);
                        frNV.setVisible(true);
                        frNV.loadInfoNhanVien(taiKhoan.getUsername(), taiKhoan.getPassword(), taiKhoan.getMaNV(), taiKhoan.getTenNV(), taiKhoan.getSdt(), taiKhoan.getGioiTinh(), taiKhoan.getNgaySinh().toString(), taiKhoan.getHinh(), taiKhoan.getLuong(), taiKhoan.getCmnd(), taiKhoan.getEmail());

                    }

                }
            }
        }
    }//GEN-LAST:event_btnDangNhapMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        
        int n = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát ?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,imgTB.getImgQuestion());
        if (n == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed
    public void hideThaoTac() {
        btnMuonTraC.setEnabled(false);
        btnThongTinNVC.setEnabled(false);
        btnsachC.setEnabled(false);
        btnDangXuatC.setEnabled(false);
        btnNhanVienC.setEnabled(false);
        btnThongKe.setEnabled(false);
    }

    public void showThaoTac() {
        btnMuonTraC.setEnabled(true);
        btnThongTinNVC.setEnabled(true);
        btnsachC.setEnabled(true);
        btnDangXuatC.setEnabled(true);
        btnNhanVienC.setEnabled(true);
        btnThongKe.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public void xoaManHinh() {

        for (JInternalFrame internalFrm : desktopPane.getAllFrames()) {
            internalFrm.dispose();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnDangNhapC;
    private javax.swing.JButton btnDangXuatC;
    private javax.swing.JButton btnMuonTraC;
    private javax.swing.JButton btnNhanVienC;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnThongTinNVC;
    private javax.swing.JButton btnsachC;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
