/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.HamXuLyChung;
import dao.NhanVienDAO;
import dao.TaiKhoanDAO;
import java.io.File;
import java.sql.Array;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import javafx.scene.paint.Color;

import javax.swing.ButtonGroup;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import pojo.ImageThongBao;
import pojo.TaiKhoan;
import sun.security.x509.AttributeNameEnumeration;

/**
 *
 * @author ADMIN
 */
public class frm_InfoNhanVien extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_InfoNhanVien
     */
    ButtonGroup btnGGioiTinh = new ButtonGroup();
    private String username, password;
    public static String image;
    TaiKhoanDAO tkDAO = new TaiKhoanDAO();
    HamXuLyChung hxl = new HamXuLyChung();
    NhanVienDAO nvDAO = new NhanVienDAO();
    Vector vctCBBNgay = new Vector();
    Vector vctCBBThang = new Vector();
    Vector vctCBBNam = new Vector();
    ImageThongBao imgTB = new ImageThongBao();

    public static String getImage() {
        return image;
    }

    public static void setImage(String image) {
        frm_InfoNhanVien.image = image;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public frm_InfoNhanVien() {
        initComponents();
        this.setSize(1400, 750);
        this.setTitle("Thông tin nhân viên");
        btnGGioiTinh.add(rbtnNam);
        btnGGioiTinh.add(rbtnNu);
        btnLuu.setEnabled(false);

        //ẩn thông tin
        hideThongTin();
        hideMatKhau();
        layCBB();
        cbbNgaySinh.setModel(new DefaultComboBoxModel(vctCBBNgay));
        cbbThangSinh.setModel(new DefaultComboBoxModel(vctCBBThang));
        cbbNamSinh.setModel(new DefaultComboBoxModel(vctCBBNam));

        //
        hideQuyTacPass();
        lbErrorPass.setVisible(false);

    }

    public void layCBB() {
        hxl.layNgayThangNam(vctCBBNgay, vctCBBThang, vctCBBNam);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txtPassOld = new javax.swing.JTextField();
        txtPassMoi = new javax.swing.JPasswordField();
        txtNhapLaiPass = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lbTBPass = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lbErrorPass = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        pnNgaySinh = new javax.swing.JPanel();
        cbbNgaySinh = new javax.swing.JComboBox<>();
        cbbThangSinh = new javax.swing.JComboBox<>();
        cbbNamSinh = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbtnNam = new javax.swing.JRadioButton();
        rbtnNu = new javax.swing.JRadioButton();
        txtLuong = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        btnLuuInfo = new javax.swing.JButton();
        btnHuyInfo = new javax.swing.JButton();
        lbTBSDT = new javax.swing.JLabel();
        lbHinh = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtFileName = new javax.swing.JTextField();
        btnDoiPass = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnShowImg = new javax.swing.JButton();
        btnHideImg = new javax.swing.JButton();
        pnQuyTac = new javax.swing.JPanel();
        lbLuuY = new javax.swing.JLabel();
        pnContentQuyTac = new javax.swing.JPanel();
        lbDK1 = new javax.swing.JLabel();
        lbDK2 = new javax.swing.JLabel();
        lbDK3 = new javax.swing.JLabel();
        lbDK4 = new javax.swing.JLabel();
        lbDK5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Change password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jPanel9.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Nhập password cũ:");
        jPanel9.add(jLabel6);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("Nhập password mới:");
        jPanel9.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("Nhập lại password mới:");
        jPanel9.add(jLabel9);

        jPanel10.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        txtPassOld.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel10.add(txtPassOld);

        txtPassMoi.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtPassMoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassMoiKeyReleased(evt);
            }
        });
        jPanel10.add(txtPassMoi);

        txtNhapLaiPass.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtNhapLaiPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNhapLaiPassKeyReleased(evt);
            }
        });
        jPanel10.add(txtNhapLaiPass);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        btnLuu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLuu.setText("Save");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel7.add(btnLuu);

        btnHuy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHuy.setText("Cancel");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel7.add(btnHuy);

        lbTBPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTBPass.setForeground(new java.awt.Color(255, 51, 51));

        jPanel13.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        lbErrorPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconError.png"))); // NOI18N
        lbErrorPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbErrorPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbErrorPassMouseExited(evt);
            }
        });
        jPanel13.add(lbErrorPass);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTBPass, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(lbTBPass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jPanel4.setLayout(new java.awt.GridLayout(8, 1, 0, 15));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Mã nhân viên:");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Họ tên:");
        jPanel4.add(jLabel2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Số điện thoại:");
        jPanel4.add(jLabel5);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Ngày sinh");
        jPanel4.add(jLabel3);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Email:");
        jPanel4.add(jLabel11);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("CMND/CCCD:");
        jPanel4.add(jLabel12);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Giới tính:");
        jPanel4.add(jLabel4);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Lương:");
        jPanel4.add(jLabel7);

        jPanel5.setLayout(new java.awt.GridLayout(8, 1, 0, 15));

        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel5.add(txtMaNV);

        txtTenNV.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel5.add(txtTenNV);

        txtSoDienThoai.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtSoDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoDienThoaiKeyReleased(evt);
            }
        });
        jPanel5.add(txtSoDienThoai);

        pnNgaySinh.setLayout(new java.awt.GridLayout(1, 3, 40, 0));

        cbbNgaySinh.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        cbbNgaySinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnNgaySinh.add(cbbNgaySinh);

        cbbThangSinh.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        cbbThangSinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnNgaySinh.add(cbbThangSinh);

        cbbNamSinh.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        cbbNamSinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnNgaySinh.add(cbbNamSinh);

        jPanel5.add(pnNgaySinh);

        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel5.add(txtEmail);

        txtCMND.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jPanel5.add(txtCMND);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        rbtnNam.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        rbtnNam.setText("Nam");
        jPanel1.add(rbtnNam);

        rbtnNu.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        rbtnNu.setText("Nữ");
        jPanel1.add(rbtnNu);

        jPanel5.add(jPanel1);

        txtLuong.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jPanel5.add(txtLuong);

        jPanel12.setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        btnLuuInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLuuInfo.setText("Save");
        btnLuuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuInfoActionPerformed(evt);
            }
        });
        jPanel12.add(btnLuuInfo);

        btnHuyInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHuyInfo.setText("Cancel");
        btnHuyInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyInfoActionPerformed(evt);
            }
        });
        jPanel12.add(btnHuyInfo);

        lbTBSDT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTBSDT.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTBSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTBSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbHinh.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Avata", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        lbHinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton4.setFont(new java.awt.Font("Times New Roman", 2, 22)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconUrl.png"))); // NOI18N
        jButton4.setText("Brown");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtFileName.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        btnDoiPass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDoiPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconChangePass.png"))); // NOI18N
        btnDoiPass.setText("Change Password");
        btnDoiPass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDoiPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiPassActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        btnCapNhat.setText("Edit Infomation");
        btnCapNhat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnShowImg.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnShowImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconShow.png"))); // NOI18N
        btnShowImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowImgActionPerformed(evt);
            }
        });

        btnHideImg.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnHideImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconHide.png"))); // NOI18N
        btnHideImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideImgActionPerformed(evt);
            }
        });

        pnQuyTac.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quy tắc", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 13))); // NOI18N

        lbLuuY.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbLuuY.setForeground(new java.awt.Color(255, 0, 51));
        lbLuuY.setText("Lưu ý (*):");

        pnContentQuyTac.setLayout(new java.awt.GridLayout(5, 1, 0, 5));

        lbDK1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbDK1.setForeground(new java.awt.Color(255, 0, 51));
        lbDK1.setText("- Tối thiểu 8 kí tự.");
        pnContentQuyTac.add(lbDK1);

        lbDK2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbDK2.setForeground(new java.awt.Color(255, 0, 51));
        lbDK2.setText("- Chứa ít nhất 1 chữ cái viết Thường.");
        pnContentQuyTac.add(lbDK2);

        lbDK3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbDK3.setForeground(new java.awt.Color(255, 0, 51));
        lbDK3.setText("- Chứa ít nhất 1 chữ cái viết Hoa");
        pnContentQuyTac.add(lbDK3);

        lbDK4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbDK4.setForeground(new java.awt.Color(255, 0, 51));
        lbDK4.setText("- Chứa ít nhất 1 chữ số.");
        pnContentQuyTac.add(lbDK4);

        lbDK5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbDK5.setForeground(new java.awt.Color(255, 0, 51));
        lbDK5.setText("- Không chứa khoảng trắng.");
        pnContentQuyTac.add(lbDK5);

        javax.swing.GroupLayout pnQuyTacLayout = new javax.swing.GroupLayout(pnQuyTac);
        pnQuyTac.setLayout(pnQuyTacLayout);
        pnQuyTacLayout.setHorizontalGroup(
            pnQuyTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuyTacLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbLuuY)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnQuyTacLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(pnContentQuyTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnQuyTacLayout.setVerticalGroup(
            pnQuyTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuyTacLayout.createSequentialGroup()
                .addComponent(lbLuuY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnContentQuyTac, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHideImg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnShowImg, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFileName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(542, 542, 542)
                        .addComponent(btnCapNhat)))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(pnQuyTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnDoiPass)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCapNhat)
                .addGap(19, 19, 19))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(lbHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnHideImg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(btnShowImg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDoiPass, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(pnQuyTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(46, 46, 46))))
        );

        jTabbedPane1.addTab("Thông tin nhân viên", jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        showThongTin();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnDoiPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiPassActionPerformed
        showMatKhau();
        btnDoiPass.setEnabled(false);
    }//GEN-LAST:event_btnDoiPassActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed

        String pOld = hxl.getHashMD5(txtPassOld.getText().trim());//Mã hóa thành chuỗi Hssh 32 kí tự theo hàm băm MD5
        String pNew = hxl.getHashMD5(txtPassMoi.getText().trim());//Mã hóa thành chuỗi Hssh 32 kí tự theo hàm băm MD5
        String pConfirm = hxl.getHashMD5(txtNhapLaiPass.getText().trim());//Mã hóa thành chuỗi Hssh 32 kí tự theo hàm băm MD5
        //Kiểm tra khi người dùng để trống
        if (txtPassOld.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu cũ không được đẻ trống","Thông báo",0,imgTB.getImgWarning());
            txtPassOld.requestFocus();
        } else if (txtPassMoi.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu mới không được đẻ trống","Thông báo",0,imgTB.getImgWarning());
            txtPassMoi.requestFocus();
        } else if (txtNhapLaiPass.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập lại mật khẩu","Thông báo",0,imgTB.getImgWarning());
            txtNhapLaiPass.requestFocus();
        } else {
            //Kiểm tra mật khẩu cũ đúng hay không
            if (pOld.equals(this.password) == false) {
                JOptionPane.showMessageDialog(rootPane, "Nhập mật khẩu cũ không đúng","Thông báo",0,imgTB.getImgWarning());
                txtPassOld.requestFocus();
            } else if (pNew.equals(pOld)) {//Kiểm trs pass mới trùng pass cũ
                JOptionPane.showMessageDialog(rootPane, "Trùng mật khẩu cũ (phải nhập pass mới)!","Thông báo",0,imgTB.getImgWarning());
                txtPassMoi.requestFocus();
            } else if (pConfirm.equals(pNew) == false) {//kiểm tra confirm pass không đúng
                JOptionPane.showMessageDialog(rootPane, "Nhập lại mật khẩu không đúng","Thông báo",0,imgTB.getImgWarning());
                txtNhapLaiPass.requestFocus();
            } else {//All hợp lệ
                boolean kt = tkDAO.doiMatKhauNhanVien(getUsername(), pConfirm);
                if (kt == true) {
                    JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thành công","Thông báo",0,imgTB.getImgCompleteGreen());
                    this.password = pConfirm;
                    hideMatKhau();
                    btnLuu.setEnabled(false);
                    btnHuy.setEnabled(false);
                    btnDoiPass.setEnabled(true);
                    hideQuyTacPass();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thất bại","Thông báo",0,imgTB.getImgError());
                }
            }

        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
//        hideThongTin();
        btnDoiPass.setEnabled(true);
        hideMatKhau();
        lbTBPass.setText("");
        hideQuyTacPass();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnHuyInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyInfoActionPerformed
        hideThongTin();
        reloadInfoNhanVien();
    }//GEN-LAST:event_btnHuyInfoActionPerformed

    private void txtSoDienThoaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKeyReleased
        String phone = txtSoDienThoai.getText();
        if (hxl.checkPhone(phone) == false) {
            lbTBSDT.setText("Phone không đúng định dạng");
        } else {
            lbTBSDT.setText("");
        }
    }//GEN-LAST:event_txtSoDienThoaiKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser fileChoose = new JFileChooser();//khai báo brownfile
        FileNameExtensionFilter filter = new FileNameExtensionFilter("HinhNhanVien", "jpg", "png");
        fileChoose.setFileFilter(filter);
        int i = fileChoose.showOpenDialog(null);
        if (i == fileChoose.APPROVE_OPTION) {
            File f = fileChoose.getSelectedFile();
            String filePath = "src/HinhNhanVien/" + f.getName();//hetName: tên file
            txtFileName.setText(filePath);
            try {
                ImageIcon icon = new ImageIcon(filePath);
                lbHinh.setIcon(icon);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnShowImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowImgActionPerformed
        ImageIcon icon = new ImageIcon(this.image);
        lbHinh.setIcon(icon);

    }//GEN-LAST:event_btnShowImgActionPerformed

    private void btnHideImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideImgActionPerformed
        ImageIcon icon = new ImageIcon("src/HinhNhanVien/default.jpg");
        lbHinh.setIcon(icon);

    }//GEN-LAST:event_btnHideImgActionPerformed

    private void btnLuuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuInfoActionPerformed
        String ID = txtMaNV.getText().trim();
        String name = txtTenNV.getText().trim();
        String day = cbbNgaySinh.getSelectedItem().toString();
        String month = cbbThangSinh.getSelectedItem().toString();
        String year = cbbNamSinh.getSelectedItem().toString();
        String birthDay = year + "-" + month + "-" + day;
        String phone = txtSoDienThoai.getText().trim();
        String email = txtEmail.getText().trim();
        String cmnd = txtCMND.getText().trim();
        String gender = "Nam";
        if (rbtnNu.isSelected()) {
            gender = "Nữ";
        }
        String img = this.image;
        if (txtFileName.getText().trim().length() > 0) {
            img = txtFileName.getText();
        }
        String info = "Name: " + name + "\nBirthday: " + birthDay + "\nPhone: " + phone + "\nEmail: " + email + "\nCMND/CCCD: " + cmnd + "\nGender: " + gender;
        //kiểm tra rỗng
        if (name.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Họ tên không được để trống", "Thông báo", 0,imgTB.getImgWarning());
            txtTenNV.requestFocus();
        } else if (phone.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Số điện thoại không được để trống", "Thông báo", 0,imgTB.getImgWarning());
            txtSoDienThoai.requestFocus();
        } else if (hxl.kTraNgayHopLe(Integer.parseInt(day), Integer.parseInt(month), Integer.parseInt(year)) == false) {
            JOptionPane.showMessageDialog(rootPane, "Ngày sinh " + birthDay + " không hợp lệ.", "Thông báo", 0,imgTB.getImgWarning());
        } else if (email.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Email không được để trống", "Thông báo", 0,imgTB.getImgWarning());
            txtEmail.requestFocus();
        } else if (cmnd.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "CMND/CCCD không được để trống", "Thông báo", 0,imgTB.getImgWarning());
            txtCMND.requestFocus();
        } else if (hxl.checkPhone(phone) == false) {
            JOptionPane.showMessageDialog(rootPane, "Số điện thoại không đúng định dạng.", "Thông báo", 0,imgTB.getImgWarning());
            txtSoDienThoai.requestFocus();
        } else if (hxl.checkEmail(email) == false) {
            JOptionPane.showMessageDialog(rootPane, "Email không đúng định dạng.", "Thông báo", 0,imgTB.getImgWarning());
            txtEmail.requestFocus();
        } else {
            //kiểm tra số điện thoại,email,cmnd/cccd đã tồn tại hay chưa
            boolean checkPhone = true;//biến ktra hợp lệ
            boolean checkEmail = true;//biến ktra hợp lệ
            boolean checkCMND = true;//biến ktra hợp lệ
            ArrayList<TaiKhoan> lstTK = tkDAO.listTaiKhoan();
            for (TaiKhoan tk : lstTK) {
                if (tk.getMaNV().equals(ID)==false && tk.getSdt().equals(phone)) {
                    checkPhone = false;//đã tồn tại => ko hợp lệ
                }
                if (tk.getMaNV().equals(ID)==false && tk.getEmail().equals(email)) {
                    checkEmail = false;//đã tồn tại => ko hợp lệ
                }
                if (tk.getMaNV().equals(ID)==false && tk.getCmnd().equals(cmnd)) {
                    checkCMND = false;//đã tồn tại => ko hợp lệ
                }
            }
            if (checkPhone == false) {
                JOptionPane.showMessageDialog(rootPane, "Số điện thoại đã tồn tại !", "Thông báo", 0,imgTB.getImgWarning());
                txtSoDienThoai.requestFocus();
            } else if (checkEmail == false) {
                JOptionPane.showMessageDialog(rootPane, "Email đã tồn tại !", "Thông báo", 0,imgTB.getImgWarning());
                txtEmail.requestFocus();
            } else if (checkCMND == false) {
                JOptionPane.showMessageDialog(rootPane, "CMND/CCCD đã tồn tại !", "Thông báo", 0,imgTB.getImgWarning());
                txtCMND.requestFocus();
            } else {//Tất cả hợp lệ
                int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc thay đổi thành:\n" + info, "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,imgTB.getImgQuestion());
                if (n == JOptionPane.YES_OPTION) {
                    boolean kq = nvDAO.UpdateNV(ID, name, birthDay, phone, gender, img, email, cmnd);
//                    System.out.println(ID+" "+name+" "+birthDay+" "+phone+" "+gender+" "+img+" "+email+" "+phone+"");
                    if (kq == false) {
                        JOptionPane.showMessageDialog(rootPane, "Đã xảy ra lỗi trong quá trình Update!", "Thất bại", 0,imgTB.getImgError());
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Thành công!", "Thông báo", 1,imgTB.getImgCompleteGreen());
                        reloadInfoNhanVien();
                        hideThongTin();
                    }
                }
            }
        }
//        System.out.println(info);
    }//GEN-LAST:event_btnLuuInfoActionPerformed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        String email = txtEmail.getText();
        if (hxl.checkEmail(email) == false) {
            lbTBSDT.setText("Email không đúng định dạng");
        } else {
            lbTBSDT.setText("");
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtNhapLaiPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNhapLaiPassKeyReleased
        String passNew = txtPassMoi.getText();
        String passConfirmNew = txtNhapLaiPass.getText();
        if (passConfirmNew.equals(passNew) == false) {
            lbTBPass.setText("Confirm Password Incorect.");
        } else {
            lbTBPass.setText("");
        }

    }//GEN-LAST:event_txtNhapLaiPassKeyReleased

    private void txtPassMoiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassMoiKeyReleased
        String passNew = txtPassMoi.getText();
        if (hxl.checkPsssword(passNew) == false) {
            lbTBPass.setText("Incorrect Password Format");
            lbErrorPass.setVisible(true);
        } else {
            lbTBPass.setText("");
            lbErrorPass.setVisible(false);
        }

    }//GEN-LAST:event_txtPassMoiKeyReleased

    private void lbErrorPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbErrorPassMouseEntered
        showQuyTacPass();
    }//GEN-LAST:event_lbErrorPassMouseEntered

    private void lbErrorPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbErrorPassMouseExited
        hideQuyTacPass();
    }//GEN-LAST:event_lbErrorPassMouseExited
    public void hideThongTin() {
        txtMaNV.setEnabled(false);
        txtTenNV.setEnabled(false);
        rbtnNam.setEnabled(false);
        rbtnNu.setEnabled(false);
        txtSoDienThoai.setEnabled(false);
        txtLuong.setEnabled(false);
        txtCMND.setEnabled(false);
        txtEmail.setEnabled(false);
        btnLuuInfo.setEnabled(false);
        btnHuyInfo.setEnabled(false);
        cbbNgaySinh.setEnabled(false);
        cbbThangSinh.setEnabled(false);
        cbbNamSinh.setEnabled(false);
        txtCMND.setEnabled(false);
        
    }

    public void hideMatKhau() {
        txtPassOld.setText("");
        txtPassMoi.setText("");
        txtNhapLaiPass.setText("");
        txtPassOld.setEnabled(false);
        txtPassMoi.setEnabled(false);
        txtNhapLaiPass.setEnabled(false);
        btnLuu.setEnabled(false);
        btnHuy.setEnabled(false);
    }

    public void showMatKhau() {
        txtPassOld.setEnabled(true);
        txtPassMoi.setEnabled(true);
        txtNhapLaiPass.setEnabled(true);

        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);
    }

    public void showThongTin() {
//        txtMaNV.setEnabled(true);
        txtTenNV.setEnabled(true);
        rbtnNam.setEnabled(true);
        rbtnNu.setEnabled(true);
        cbbNgaySinh.setEnabled(true);
        txtEmail.setEnabled(true);
        cbbThangSinh.setEnabled(true);
        cbbNamSinh.setEnabled(true);
        txtSoDienThoai.setEnabled(true);
        btnLuuInfo.setEnabled(true);
        btnHuyInfo.setEnabled(true);
        txtCMND.setEnabled(true);
    }

    void hideQuyTacPass() {
        pnQuyTac.setVisible(false);
    }

    void showQuyTacPass() {
        pnQuyTac.setVisible(true);
    }

    public void loadInfoNhanVien(String tk, String mk, String maNV, String tenNV, String sdt, String gioiTinh, String ngaySinh, String img, int luong, String cmnd, String email) {
        setUsername(tk);
        setPassword(mk);
        this.image = img;
        ImageIcon icon = new ImageIcon(img);
        lbHinh.setIcon(icon);
        txtMaNV.setText(maNV);
        txtTenNV.setText(tenNV);
        txtEmail.setText(email);
        txtCMND.setText(cmnd);

        DecimalFormat df = new DecimalFormat("###,###,###");//định dạng kiểu tiền tệ 
        String salary = df.format(luong) + " VND";
        txtLuong.setText(String.valueOf(salary));
        //Cắt chuỗi ngày sinh ra DD, MM, YYYY
        String date[] = ngaySinh.split("-");
        String ngay = date[2];
        String thang = date[1];
        String nam = date[0];

        int indexD = hxl.timViTriVctcbb(vctCBBNgay, ngay);
        int indexMM = hxl.timViTriVctcbb(vctCBBThang, thang);
        int indexYYYY = hxl.timViTriVctcbb(vctCBBNam, nam);
        cbbNgaySinh.setSelectedIndex(indexD);
        cbbThangSinh.setSelectedIndex(indexMM);
        cbbNamSinh.setSelectedIndex(indexYYYY);

        txtSoDienThoai.setText(sdt);

        if (gioiTinh.equals("Nam")) {
            rbtnNam.setSelected(true);
        } else {
            rbtnNu.setSelected(true);
        }
//        System.out.println(this.username);
//        System.out.println(this.password);
    }

    public void reloadInfoNhanVien() {
        ArrayList<TaiKhoan> lstTK = tkDAO.listTaiKhoan();
        for (TaiKhoan tk : lstTK) {
            if (tk.getUsername().equals(this.username)) {
                loadInfoNhanVien(tk.getUsername(), tk.getPassword(), tk.getMaNV(), tk.getTenNV(), tk.getSdt(), tk.getGioiTinh(), tk.getNgaySinh().toString(), tk.getHinh(), tk.getLuong(), tk.getCmnd(), tk.getEmail());
                break;
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDoiPass;
    private javax.swing.JButton btnHideImg;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnHuyInfo;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuuInfo;
    private javax.swing.JButton btnShowImg;
    private javax.swing.JComboBox<String> cbbNamSinh;
    private javax.swing.JComboBox<String> cbbNgaySinh;
    private javax.swing.JComboBox<String> cbbThangSinh;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbDK1;
    private javax.swing.JLabel lbDK2;
    private javax.swing.JLabel lbDK3;
    private javax.swing.JLabel lbDK4;
    private javax.swing.JLabel lbDK5;
    private javax.swing.JLabel lbErrorPass;
    private javax.swing.JLabel lbHinh;
    private javax.swing.JLabel lbLuuY;
    private javax.swing.JLabel lbTBPass;
    private javax.swing.JLabel lbTBSDT;
    private javax.swing.JPanel pnContentQuyTac;
    private javax.swing.JPanel pnNgaySinh;
    private javax.swing.JPanel pnQuyTac;
    private javax.swing.JRadioButton rbtnNam;
    private javax.swing.JRadioButton rbtnNu;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtNhapLaiPass;
    private javax.swing.JPasswordField txtPassMoi;
    private javax.swing.JTextField txtPassOld;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
